{% set version = "12.1.0" %}

package:
  name: ripgrep
  version: {{ version }}

source:
  url: https://github.com/BurntSushi/ripgrep/archive/{{ version }}.tar.gz
  sha256: ca2d11dd7b7346734d47ad8073468e9c409fbe85842a608d372b8d4fb36be291

build:
  number: 0

requirements:
  build:
    - rust
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]

test:
  commands:
    - rg --help

about:
  home: https://github.com/BurntSushi/ripgrep
  license: MIT
  summary: ripgrep recursively searches directories for a regex pattern
  license_family: MIT
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - dbast
    - seanyen
