{% set version = "12.0.1" %}

package:
  name: ripgrep
  version: {{ version }}

source:
  url: https://github.com/BurntSushi/ripgrep/archive/{{ version }}.tar.gz
  sha256: 5be34aa77a36ac9d8f1297a0d97069e4653e03f61c67d192cee32944cd2b6329

build:
  number: 1

requirements:
  build:
    - rust
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]

test:
  commands:
    - rg --help

about:
  home: https://github.com/BurntSushi/ripgrep
  license: MIT
  summary: ripgrep recursively searches directories for a regex pattern
  license_family: MIT
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - dbast
